server:
  port: 8085

spring:
  application:
    name: currencyexchange
  r2dbc:
    url: r2dbc:h2:mem:///currencyexchangedb
    username: test
    password: test
  profiles:
    active: dev

springdoc:
  swagger-ui:
    enabled: true


external-apis:
  users-api:
    base-url: https://gorest.co.in
    users-path: /public/v2/users
    id-key: id

jwt-auth:
  secret: XCkeB9aPz2vniihuCUyVYtVS4p0EXZ0Q



